 /* QUESTÃO 01 */
 
 SELECT VEN_NOME, SEX_TIPO FROM TB_VENDEDORES 
 
 JOIN TB_SEXOS ON VEN_SEX_CODIGO = SEX_CODIGO;
 
 /* QUESTÃO 02 */
 
 SELECT CID_CIDADE, EST_NOME FROM TB_CIDADES
 
 JOIN TB_ESTADOS ON CID_EST_CODIGO = EST_CODIGO;
 
 /* QUESTÃO 03 */
 
 SELECT PRO_NOME, MAR_NOME FROM TB_PRODUTOS
 
 JOIN TB_MARCAS ON PRO_MAR_CODIGO = MAR_CODIGO;
 
 /* QUESTÃO 04 */
 
 SELECT PRO_NOME, DEP_NOME FROM TB_PRODUTOS
 
 JOIN TB_DEPARTAMENTOS ON PRO_DEP_CODIGO = DEP_CODIGO;
 
 /* QUESTÃO 05 */
 
 SELECT CLI_NOME, CLF_CPF, CLF_RG FROM TB_CLIENTES
 
 JOIN TB_CLIFISICO ON CLF_CLI_CODIGO = CLI_CODIGO;
 
 /* QUESTÃO 06 */
 
 SELECT FOR_NOME, COM_CODIGO, COM_NT_FISCAL FROM TB_FORNECEDORES
 
 JOIN TB_COMPRAS ON COM_FOR_CODIGO = FOR_CODIGO;
 
 /* QUESTÃO 07 */
 
 SELECT CLI_NOME, COM_CODIGO, COM_NT_FISCAL, COM_DATA FROM TB_CLIENTES
 
 JOIN TB_COMPRAS ON COM_CODIGO = CLI_CODIGO;
 
 /* QUESTÃO 08 */
 
 SELECT VEN_NOME, COM_CODIGO, COM_NT_FISCAL, COM_DATA, VED_CODIGO FROM TB_VENDEDORES
 
 JOIN TB_COMPRAS ON COM_CODIGO = VEN_CODIGO
 
 JOIN TB_VENDAS ON VED_VEN_CODIGO = VEN_CODIGO;
 
 /* QUESTÃO 09 */
 
 SELECT 
    CLI_NOME, VEN_NOME, VED_CODIGO, VED_NT_FISCAL
FROM
    TB_CLIENTES
        JOIN
    tb_vendas ON VED_CLI_CODIGO = CLI_CODIGO
        JOIN
    tb_vendedores ON VED_VEN_CODIGO = VEn_CODIGO;

